# Zizmor config
rules:
  unpinned-uses:
    config:
      policies:
        # Allow pin by ref/tag
        actions-rust-lang/setup-rust-toolchain: ref-pin
        github/codeql-action/*: ref-pin
        actions/*: ref-pin
